### ISSUE TITLE
questions (within questions dir) should be organized by exam number

### ISSUE THREAD

**Issue by chrissprague** [rit-csc/csc_exam_reviews#19]
e.g.
    &nbsp;&nbsp;&nbsp;&nbsp;questions/
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;e1/
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;e1q1
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;e1q2
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;e2/
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;e2q1
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;e2q2

**Comment by khipkin** [comment]
@chrissprague It makes more sense to organize by topic.  The entire point of having the current organizational structure is so questions can be easily used on multiple exams.  Tying questions to specific exams defeats the entire purpose of the refactor and brings code/question re-usability back down to zero.

**Comment by khipkin** [comment]
e.g.
    questions/
        topic1/
              q1
              q2
        topic2/
              q1
              q2
