### ISSUE TITLE
142 no longer uses Swing, need to change questions to use JavaFX

### ISSUE THREAD

**Issue by RaineForest** [rit-csc/csc_exam_reviews#20]

**Comment by chrissprague** [comment]
Addressed in part @https://github.com/rit-csc/csc_exam_reviews/commit/a908829db60233be6615774e0a277e81e8515f62 :womans_hat:

**Comment by GavinNishizawa** [comment]
updated swing question in exam 2 review to use javafx instead.

**Comment by chrissprague** [comment]
fixed @ https://github.com/rit-csc/csc_exam_reviews/commit/0d4cf2ef8d4051bb26170c4bafdeb195d352b1f9, https://github.com/rit-csc/csc_exam_reviews/commit/a908829db60233be6615774e0a277e81e8515f62
