### ISSUE TITLE
Rename the repository "exam_reviews"

### ISSUE THREAD

**Issue by zg** [rit-csc/csc_exam_reviews#25]

**Comment by khipkin** [comment]
In my opinion, this is not a big enough problem to justify the hassle required to make the change.

**Comment by EricFalkenberg** [comment]
AFAIK the repo name can be changed through Github's UI and that's the only step necessary. Github handles the redirects when anyone tries to access the repo via its old address.

**Comment by chrissprague** [comment]
@EricFalkenberg you are correct, and for this repo it is probably fine, but with the website repo, it indeed would be a hassle to make sure everything works properly after a rename on the server

**Comment by khipkin** [comment]
@EricFalkenberg I didn't know that!  It handles redirects indefinitely?

Also I agree with @chrissprague that we should leave the website repo alone.

**Comment by chrissprague** [comment]
@khipkin name redirecting: https://help.github.com/articles/what-happens-when-i-change-my-username/#changes-that-occur-automatically (this article addresses username changes but I've worked with repositories where the organization changes and it applies there too)

**Comment by khipkin** [comment]
@chrissprague That article talks about changing your username; @zg is talking about renaming the repository.

**Comment by YawarRaza7349** [comment]
Will changing the repo name in GitHub's UI also automatically handle any necessary changes in the local repos' origin URL setting?

**Comment by EricFalkenberg** [comment]
@khipkin I changed the name on of [Chip8-emu](http://github.com/EricFalkenberg/Chip8-emu)
to [chip8_emulator](http://github.com/EricFalkenberg/chip8_emulator) more than 2 years ago now and it still works so I would assume it works indefinitely

**Comment by EricFalkenberg** [comment]
@YawarRaza7349 when you push to or pull from a remote branch that resides at an address that has been changed, Github will handle the redirect there too. So if you pull from the old address, it will return contents from the new address

**Comment by chrissprague** [comment]
I wouldn't mind re-opening a discussion on renaming this repo (and possibly others for the sake of consistency), but I'm closing this for now.
